### ISSUE TITLE
Questions about ruler conversion

### ISSUE THREAD

**Issue by lalulalulearing** [Gene-Weaver/LeafMachine2#17]
Hello, I am using LeafMachine2 for leaf measurements, but I am a bit concerned about the accuracy of ruler recognition. To verify the accuracy of the results, I would like to understand what the conversion_mean means in the unit conversion process. Does it always represent the pixel length of one centimeter in actual size?

**Comment by Gene-Weaver** [comment]
Our methods detect the distance, in pixels, between tick marks or blocks of whatever unit size is present in the ruler. If the algorithm is successful in isolating the unit markers, then our pixel-to-metric conversion factor (CF) is more precise than manually determining the scale using something like ImageJ, since we detect all markers and take the geometric mean of all the distances. Recently, we also predict the CF based on the image resolution. As long as the image's longest dimension is greater than 3000 pixels and represents a typical herbarium specimen, then the predicted CF will have up to a 10% error. The predicted CF is calculated for all images even if the calculated CF fails. Our published paper and the supplemental material has all of the details:
[Appendix S2](https://bsapubs.onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1002%2Faps3.11548&file=aps311548-sup-0002-APPS-D-23-00032_SupportingInformation_AppS2.docx)
[Appendix S3](https://bsapubs.onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1002%2Faps3.11548&file=aps311548-sup-0003-APPS-D-23-00032_SupportingInformation_AppS3.docx)
[Paper](https://bsapubs.onlinelibrary.wiley.com/doi/10.1002/aps3.11548)
