### ISSUE TITLE
3.12 cannot be supported due to pathtools dependency

### ISSUE THREAD

**Issue by mpitblado** [Gene-Weaver/LeafMachine2#6]
Due to the requirement of pathtools, we have found that this cannot run using Python 3.12. See https://github.com/gorakhargosh/pathtools/issues/13. This may prompt a change in text within the README to mention this, so that users know to start the virtual environment with python 3.11 or lower.

I am not sure the status of the pathtools repository, it hasn't had a commit in 8 years.

**Comment by Gene-Weaver** [comment]
In commit [216c5b1](https://github.com/Gene-Weaver/LeafMachine2/commit/216c5b107e16079aff47ab8f649826a941ea492b) I removed some unused packages that ended up in the requirements.txt including pathtools. I have not validated Python 3.12, but it might play nicely now. Anyway, I added to the readme that beyond 3.11 may not be stable since some of LeafMachine2 relies on older versions of some packages, especially PyTorch (which will work with PyTorch 2.X+ if you play around with updating some dependencies).
